### ISSUE TITLE
Colcon auto completion

### ISSUE THREAD

**Issue by AlfredMoore** [fluentrobotics/ros-devcontainer#1]
maybe we can add an apt package `python3-colcon-common-extensions` for colcon auto completion

**Comment by elvout** [comment]
`humble` already includes this package from the `osrf/ros:humble-desktop-full` image and it's being installed using pip in `humble-cu118`:
https://github.com/fluentrobotics/ros-devcontainer/blob/4687a6ec526e0456e16183c3bd682058b000621b/Dockerfile#L40

@AlfredMoore which branch and shell are you using?

**Comment by elvout** [comment]
Perhaps for consistency, the `humble-cu118` branch could also use the apt package for installation instead of pip.

**Comment by AlfredMoore** [comment]
> which branch and shell are you using?

f5781bc, in humble-cu118. But the colcon completion does not work with the pip version 
`RUN pip3 install --upgrade colcon-common-extensions virtualenv`. 

After I apt install the `python3-colcon-common-extensions`, and `source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash` in `.bashrc`, the colcon auto completion works.

**Comment by elvout** [comment]
Interesting, if you have a clean repository, could you run `git fetch --all && git reset --hard origin/humble-cu118` and see if it works after rebuilding the container? Currently we're updating branches using rebases and force pushes, which isn't ideal, but it keeps the commit graph linear.

**Comment by elvout** [comment]
> After I apt install the `python3-colcon-common-extensions`, and `source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash` in `.bashrc`, the colcon auto completion works.

Oh, you'll probably have to have that in your .bashrc regardless of the installation method. In zsh there's a known bug for completions in humble that requires a workaround.

**Comment by elvout** [comment]
Ah, with pip, the file is at `/usr/local/share/colcon_argcomplete/hook/colcon-argcomplete.bash` instead

**Comment by AlfredMoore** [comment]
> you'll probably have to have that in your .bashrc regardless of the installation method.

Maybe the `apt install python3-colcon-common-extensions` and `pip3 install colcon-common-extensions` uses different `source **-argcomplete.bash`. Because I cannot source it without `apt install python3-colcon-common-extensions`

**Comment by AlfredMoore** [comment]
> Ah, with pip, the file is at /usr/local/share/colcon_argcomplete/hook/colcon-argcomplete.bash instead

yes, I think that is the reason

**Comment by elvout** [comment]
Ok, I'll change the installation method from pip to apt; will test on zsh and then push in a couple minutes if it works for me

**Comment by elvout** [comment]
Ok; I force-pushed an update -- could you see if completions work after rebuilding the container?

Also if you have an ament workspace, could you source `install/setup.bash` and see if completions break? On zsh, sourcing `install/setup.zsh` breaks completions, but there are shell hacks in both bash and zsh to reload completions when the shell prompt is redrawn.

**Comment by AlfredMoore** [comment]
I will check it tomorrow. Thx :)

**Comment by AlfredMoore** [comment]
maybe we also need the `ros-humble-xacro` apt package for URDF? (Not in the ros-humble-desktop)

**Comment by elvout** [comment]
The `humble-cu118` branch was updated to `ros-humble-desktop-full` a while ago (although it's not in the commit history) and has that package on my end. I'm considering an alternative organization of the repository that won't require force pushes/pulls, but for the time being, could you hard reset your branch to `origin/humble-cu118` (should be `3d65862`) and rebuild the image?

**Comment by AlfredMoore** [comment]
> The `humble-cu118` branch was updated to `ros-humble-desktop-full` a while ago (although it's not in the commit history) and has that package on my end. I'm considering an alternative organization of the repository that won't require force pushes/pulls, but for the time being, could you hard reset your branch to `origin/humble-cu118` (should be `3d65862`) and rebuild the image?

It works! :)
